# kubectl apply -f service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-k8s-api-service
  namespace: python-api-namespace
spec:
  type: LoadBalancer
  selector:
    app: python-k8s-api
  ports:
    - protocol: TCP 
      port: 80 # Port on which the service listens in the cluster
      targetPort: 5000 # Port on which the container listens in the pod
      nodePort: 30080 # Port on which the service listens on the nodes